services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 8001:80/tcp
      - 8002:443/tcp
    volumes:
      - /data/docker/adguard/workdir:/opt/adguardhome/work
      - /data/docker/adguard/confdir:/opt/adguardhome/conf
    restart: unless-stopped